services:
  traefik:
    # The latest official supported Traefik docker image
    image: docker.io/traefik:v3.2
    # Enables the Traefik Dashboard and tells Traefik to listen to docker
    # --providers tell Traefik to connect to the Docker provider
    # enable --log.level=INFO so we can see what Traefik is doing in the log files
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "--log.level=INFO"
      - "--entryPoints.web.address=:80"
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
# Add the whoami service
  whoami:
     # A container that exposes an API to show its IP address
     image: docker.io/traefik/whoami
     # We set a label to tell Traefik to assign a hostname to the new service
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
       - "traefik.http.routers.whoami.entrypoints=web"
       - "traefik.http.services.my-service.loadbalancer.server.port=80"

       